#!/bin/bash

NAME=`basename $0`

if [[ "$PLTHOME" == "" ]]; then
   echo "$NAME: PLTHOME has not been set."
   exit -1
fi

BUILDDIR="$PLTHOME/racket/src/build"

rm -rf "$BUILDDIR"
pushd "$PLTHOME"
CPPFLAGS=-I/opt/local/include make
popd
