#!/bin/bash
#
# Put this script in your bin/ folder and point
# PATH_TO_PLT_BIN to its location

NAME="$1"
shift 
if [[ "$PLTHOME" == "" ]]; then
   echo "$NAME: PLTHOME has not been set."
   exit -1
else
   BIN="$PLTHOME/racket/bin/$NAME"
   OLDBIN="$PLTHOME/bin/$NAME"
   if [[ -x "$BIN" ]]; then
       exec "$BIN" "$@"
   elif [[ -x "$OLDBIN" ]]; then
       exec "$OLDBIN" "$@"
   else
       echo "$NAME: no executable at \"$BIN\"."
       exit -1
   fi
fi
