#!/bin/bash

NAME=`basename $0`

if [[ "$PLTHOME" == "" ]]; then
   echo "$NAME: PLTHOME has not been set."
   exit -1
fi

BUILDDIR="$PLTHOME/racket/src/build"
OLDBUILDDIR="$PLTHOME/src/build"

if [[ -d "$PLTHOME/pkgs" ]]; then
   rm -rf "$BUILDDIR"
   pushd "$PLTHOME"
   CPPFLAGS=-I/opt/local/include make
   popd
else
   rm -rf "$OLDBUILDDIR"
   mkdir "$OLDBUILDDIR"
   pushd "$OLDBUILDDIR"
   CPPFLAGS=-I/opt/local/include ../configure && make -j2 && make install
   popd
fi
